server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: store-service
          uri: lb://store-service
          predicates:
            - Path=/store/**
          filters:
            - RewritePath=/store/(?<path>.*), /$\{path}