spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:~/h2/store_service
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog-master.xml
    drop-first: true
  kafka:
    bootstrapServers: localhost:29092
    topics:
      order: product-order
    consumer:
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/